"use client";
import { useState, useEffect } from "react";
import CollapsibleSection from "@/components/base/CollapsibleSection";
import EditableTextArea from "../base/EditableTextArea";

export default function StudyComponent() {
  const [description, setDescription] = useState<string>("");
  const [title, setTitle] = useState<string>("");

  // Assuming this is where you fetch or generate a description from the LLM
  const fetchDescriptionFromLLM = async () => {
    const llmDescription =
      "Superconducting Magnetic Energy Storage (SMES) stores electrical energy..."; // Example LLM output
    setDescription(llmDescription); // Update state with LLM-generated description
  };

  // Assuming this is where you fetch or generate the title from the LLM
  const fetchTitleFromLLM = async () => {
    const llmTitle = "Example Title Generated by LLM"; // Example LLM output for the title
    setTitle(llmTitle); // Update state with LLM-generated title
  };

  // Call this function to fetch the description when the component is mounted
  useEffect(() => {
    fetchDescriptionFromLLM();
    fetchTitleFromLLM();
  }, []);

  return (
    <div className="w-full overflow-auto">
      <div className="min-w-[400px] max-w-[850px] rounded overflow-hidden border border-grey">
        <CollapsibleSection title="Title">
          <EditableTextArea
            value={title} // Set the current state value as the textarea value
            onChange={(newTitle) => setTitle(newTitle)} // Update the state on user input
            placeholder="Enter Title here..."
            rows={3} // Set dynamic rows for the description section
          />
        </CollapsibleSection>

        <CollapsibleSection title="Description">
          <EditableTextArea
            value={description} // Set the current state value as the textarea value
            onChange={(newDescription) => setDescription(newDescription)} // Update the state on user input
            placeholder="Enter description here..."
            rows={20} // Set dynamic rows for the description section
          />
        </CollapsibleSection>
      </div>
    </div>
  );
}
